version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "imptodefeat@gmail.com"
            git config --global user.name "maany"
            echo "machine github.com login maany password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=maany npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website