version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "maany@users.noreply.github.com"
            git config --global user.name "maany"
            export GIT_USER=maany
            echo "machine github.com login maany password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=<GIT_USER> yarn run publish-gh-page

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
